exclude: integration_test/statictest/static/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v1.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
  - repo: https://github.com/ambv/black.git
    rev: 25.1.0
    hooks:
      - id: black
        entry: black -l 120 -t py311
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
  - repo: https://github.com/prettier/prettier.git
    rev: 1.14.0
    hooks:
      - id: prettier
        files: \.(css|less|scss|ts|tsx|graphql|gql|js|jsx|md)$
