language: python
python:
- "3.10"
- "3.11"
- "3.12"
- "3.13"
- "3.14"
matrix:
  allow_failures:
  - python: "3.14"
install: python setup.py develop
script:
- python setup.py test
- cd integration_test && python manage.py test
